### ISSUE TITLE
Fails with "missing gitlab-ci config"

### ISSUE THREAD

**Issue by danieldunderfelt** [appleboy/gitlab-ci-action#4]
I tried to use this action in a Github actions workflow, but despite following the instructions and giving all the parameters, it always fails with "missing gitlab-ci config". Am I missing something?

The pipeline runs fine on Gitlab when I trigger it manually, I am not missing a gitlab-ci config.

**Comment by billux** [comment]
I ran into the same issue and it was because I passed a wrong variable name to the docker. We should set `GITLAB_PROJECT_ID` instead of `GITLAB_ID` (the example in the README is incorrect).

**Comment by itzikgb** [comment]
What is the use case here? why would you want to trigger GitLab pipeline from GH Actions?

**Comment by Just-Insane** [comment]
@billux were you able to resolve this for pull requests? It is working when I (as the project owner) push a commit, but when a pull request receives a commit, it gives the same error.

I don't see either GITLAB_ID or GITLAB_PROJECT_ID in the output of the job.

**Comment by appleboy** [comment]
maybe see the reference: https://securitylab.github.com/research/github-actions-preventing-pwn-requests

**Comment by Just-Insane** [comment]
Ah, that makes a lot of sense, thanks for the information!
