### ISSUE TITLE
Does it work for PRs from forks?

### ISSUE THREAD

**Issue by pawamoy** [appleboy/gitlab-ci-action#5]
Currently, GitLab CI is not triggered for PRs from GitHub forks, see https://gitlab.com/gitlab-org/gitlab/issues/5667

Would this action allow to integrate PRs from forks?

**Comment by pawamoy** [comment]
Not interested anymore, closing!

**Comment by Just-Insane** [comment]
I would also like to know if this is possible, as it is my main usecase.
